export const ActionTypes = {
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_ERROR: "USER_LOGIN_ERROR",
  USER_TOKEN: "USER_TOKEN",
  USER_LOG_OUT: "USER_LOG_OUT",



  URL_SUBMITTED_SUCCESS: "URL_SUBMITTED_SUCCESS",
  URL_PULL_SUCCESS : "URL_PULL_SUCCESS",
};
